In [1]:
import pandas as pd

DATA_PATH = "../data/raw/"

orders = pd.read_csv(DATA_PATH + "orders.csv")
order_products_prior = pd.read_csv(DATA_PATH + "order_products__prior.csv")
products = pd.read_csv(DATA_PATH + "products.csv")

In [2]:
user_features = orders.groupby("user_id").agg({
    "order_number": "max"
}).rename(columns={
    "order_number": "total_orders"
})

user_features.head()

         total_orders
user_id
1                  11
2                  15
3                  13
4                   6
5                   5

In [4]:
avg_days = orders.groupby("user_id")["days_since_prior_order"].mean()

user_features["avg_days_between_orders"] = avg_days

In [5]:
user_order = order_products_prior.merge(
    orders[["order_id", "user_id"]],
    on="order_id",
    how="left"
)

reorder_ratio = user_order.groupby("user_id")["reordered"].mean()

user_features["reorder_ratio"] = reorder_ratio

In [ ]:
user_features.head()

         total_orders  avg_days_between_orders  reorder_ratio
user_id
1                  11                19.000000       0.694915
2                  15                16.285714       0.476923
3                  13                12.000000       0.625000
4                   6                17.000000       0.055556
5                   5                11.500000       0.378378

In [7]:
user_features.to_csv(
    "../data/processed/user_features.csv"
)